### ISSUE TITLE
Solve Overflow Horizontally

### ISSUE THREAD

**Issue by devjainofficial** [devjainofficial/React-Portfolio#6]
![image](https://github.com/devjainofficial/React-Portfolio/assets/69387311/e68a5577-5fe0-4d46-98a9-02035077e686)

**Comment by Baburao-sanivada** [comment]
Mannnn your portfolio Website looks Awesome Can i Work on this issue?

**Comment by Baburao-sanivada** [comment]
Hello @devjainofficial can you provide some more Description on the issue so that i can start working on this issue?

**Comment by devjainofficial** [comment]
Actually, you just need to add Overflow: hidden.
That is all.

**Comment by Baburao-sanivada** [comment]
ok thank you

**Comment by Baburao-sanivada** [comment]
Hello @devjainofficial i wrote overflow-x hidden for body in index.css file but due to this two vertical sroll bras are appearing
![Screenshot (202)](https://github.com/devjainofficial/React-Portfolio/assets/118034087/f266bc73-56ae-41c2-80db-a9b7c40d143a)
![Screenshot (203)](https://github.com/devjainofficial/React-Portfolio/assets/118034087/bbac5363-3229-4b12-8722-651050ee6666)

Could you help me with this?

**Comment by devjainofficial** [comment]
Push the code, I'll take care of that.

**Comment by Baburao-sanivada** [comment]
Hey @devjainofficial I made a Pr Please look into it
